name: panaséa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42704
title: panaséa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23306a'
    - '#cccdcb'
    - '#4a5481'
    - '#6c6ca8'
    - '#afadc3'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.28503342950716615
purpose: []
