title: panaséa
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7717508
  brandStrength: 0.8845327
  rhythmicContrast: 0.4355532
  brandColors:
    - '#FFFFFF'
    - '#A1A1A1'
    - '#C8C8C8'
    - '#2A2D85'
    - '#55557D'
  lightness: 0.6074114
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-80116173-1
  facebook: null
favicon: null
name: panaséa
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1756176
layout_spectrum: 1
