name: panaséa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42704
title: panaséa
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-80116173-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#A1A1A1'
    - '#C8C8C8'
    - '#2A2D85'
    - '#55557D'
  brandStrength: 0.5
  lightness: 0.3668098
  saturation: 0.625
  rhythmicContrast: 0.2850334
purpose: []
